# Generated by Django 5.1.4 on 2025-03-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_faq_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='insurance',
        ),
    ]
