# Generated by Django 5.1.4 on 2025-03-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_patients_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
