# Generated by Django 5.1.4 on 2025-03-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_users_id_address_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='assets/img/def.jpeg', null=True, upload_to='users/profiles'),
        ),
    ]
