# Generated by Django 5.1.4 on 2025-04-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_users_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='doctor/profiles/download.jpg', null=True, upload_to='users/profiles'),
        ),
    ]
