# Generated by Django 5.1.4 on 2025-04-28 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_users_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address', models.AutoField(primary_key=True, serialize=False)),
                ('address_line', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='assets/img/def.jpeg', null=True, upload_to='users/profiles'),
        ),
        migrations.AddField(
            model_name='users',
            name='id_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
    ]
